Added geo + rawResult returned in callback
dericcain/google-address-autocomplete pull request #9
Opened 2017-12-12 16:01 UTC by Braunson

Referencing issue #8

This PR does not introduce any breaking changes (except the package.json scripts that have been adjusted for Windows)

- Second parameter returns the geo lat/lng object
- Third parameter returns the raw google response

2017-12-19 13:08 UTC, ghost requested changes

2017-12-19 13:08 UTC, ghost commented on src/index.js
> +      geometry
Nice job on the es6! One small thing - this variable can be added to the destructured set above since we are already destructuring `this.autocomplete.getPlace()`. So, it can be:
```JavaScript
const {
    address_components,
    formatted_address,
    geometry
} = this.autocomplete.getPlace();
```
And then you can get rid of the whole geometry block that was added.

2017-12-19 13:08 UTC, ghost commented on src/index.js
> +    const rawObject = this.autocomplete.getPlace();
Now seeing that you are getting the `rawResult` from here, this is what I would do to clean this up a bit. 
1. Create a variable `rawResult`
2. Desctructure from that variable to get all of the other variables needed. What that does is allow us to only call the `this.autocomplete.getPlace()` one time. (see code snippet below for explanation)
3. The `rawResult will be passed as the second parameter to the callback. More on that later, but in a nutshell, we will only be passing 2 params to the callback.

```JavaScript
// This should get us all the variables we need
const rawResult = this.autocomplete.getPlace();
const { address_components, formatted_address, geometry: { location: { lat, lng } } } = rawResult;
```
That will create `address_components`, `formatted_address`, `lat` and `lng` variables for us.

2017-12-19 13:08 UTC, ghost commented on src/index.js
> +    const geoFormatted = Object.assign({}, geoObject);
Since you are not combining any objects here, you really don't need this. `Object.assign()` is good for creating a new object when combining objects instead of mutating an object. It would probably be better to use the [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) here, and I probably will fix it later on (nothing you have to worry about).

2017-12-19 13:08 UTC, ghost commented on src/index.js
> +    const rawResult = Object.assign({}, rawObject);
Again, don't really need this.

2017-12-19 13:08 UTC, ghost commented on src/index.js
> +    this.callback(resultFormatted, geoFormatted, rawResult);
So, for this. I know we discussed having 2 params and I would like to stick with that. So, what we could do is add the `lat` and `lng` to the first param because I could see people using that one and then just return the `rawResult` for the second param. I think this keeps the API nice and concise and makes it very flexible.

2017-12-20 21:20 UTC, Braunson commented
@dericcain Ok I've made some of the changes however I'm stuck at this point. When linting I get..

```
  79:11  error  'lat' is assigned a value but never used  no-unused-vars
  80:11  error  'lng' is assigned a value but never used  no-unused-vars
```

2017-12-21 11:58 UTC, dericcain commented
@Braunson The reason you are getting the linting errors is because on line 79 and 80, where you are destructuring the `lat` and `lng` - those variables are never used. What needs to happen is you should delete line 91 `const geoObject = resultRaw.geomatry.location;` and change the `addressObject` constant to look like this:
```JavaScript
const addressObject = {
      streetNumber: '',
      streetName: '',
      cityName: '',
      stateAbbr: '',
      zipCode: '',
      coordinates: { lat, lng },
};
```
That will pass your `npm run lint` and format the output as needed. So, the full method will look like this:
<details>
  <summary>`extractAddress()` (click to expand)</summary>

```JavaScript
extractAddress() {
    const componentForm = {
      street_number: 'short_name',
      route: 'long_name',
      locality: 'long_name',
      administrative_area_level_1: 'short_name',
      country: 'long_name',
      postal_code: 'short_name',
    };

    const resultRaw = this.autocomplete.getPlace();
    const {
      address_components,
      formatted_address,
      geometry: {
        location: {
          lat,
          lng
        }
      }
    } = resultRaw;
    const addressObject = {
      streetNumber: '',
      streetName: '',
      cityName: '',
      stateAbbr: '',
      zipCode: '',
      coordinates: { lat, lng, }
    };
  
    // Need to loop over the results and create a friendly object
    for (let i = 0; i < address_components.length; i++) {
      const addressType = address_components[i].types[0];
      if (componentForm[addressType]) {
        switch (addressType) {
          case 'street_number':
            addressObject.streetNumber = address_components[i].long_name;
            break;
          case 'route':
            addressObject.streetName = address_components[i].long_name;
            break;
          case 'locality':
            addressObject.cityName = address_components[i].long_name;
            break;
          case 'administrative_area_level_1':
            addressObject.stateAbbr = address_components[i].short_name;
            addressObject.state = address_components[i].long_name;
            break;
          case 'postal_code':
            addressObject.zipCode = address_components[i].long_name;
            break;
          case 'country':
            addressObject.countryAbbr = address_components[i].short_name;
            addressObject.country = address_components[i].long_name;
            break;
          default:
            break;
        }
      }
    }

    const resultFormatted = Object.assign({}, addressObject, {
      formattedAddress: formatted_address,
    });

    // This is where we check for the callback and then call it, passing our resutls
    this.callback(resultFormatted, resultRaw);
  }
```
</details>

2017-12-21 11:59 UTC, ghost approved these changes
👍 👍 👍

2017-12-21 12:10 UTC, ghost requested changes
Awesome progress on this! Looks like all you need to do is fix the one small issue with the lat and lng and this PR will be good to go!

2017-12-21 20:01 UTC, Braunson commented
@dericcain Updated, thank you!

Just a thought, thought the raw response be an object like the formatted one or should we keep it an array?

2017-12-21 22:00 UTC, ghost approved these changes
Nice work! This will be very useful.

2017-12-21 22:00 UTC, merged

2017-12-21 22:01 UTC, dericcain commented
@Braunson Since we are explicitly returning the raw result, I am okay with how it is returned.

Thanks a ton for you help with this!